In [ ]:
==============EDA========================
1) pandas         : Dataframe or data applications
2) numpy          : numerical python for math operations
3) matplotlib     : For plots graphs
4) seaborn        : For plots graphs
5) Bokhe          : For plots 
6) plotly         : For plots 

==============ML========================
7) Scikit learn(Sklearn)  : ML models
8) stats                  : statistical models

=======Data retrival from sql scrapping=====
9) Sqlite          : connect with database
10) Beautiful soup : scrap the data from website
11) websocket      : scrap

============Deep learning/computer vision=======
12) Tensorflow     : Google
13) Keras          : DL models
14) OpenCV         : Image operations
15) Pillow(PIL)    : Image operations
16) Pytorch        : Facebook
17) Pretrained model
    VGG16
    Mobilenet
    RESNET
    RCNN
    MASKRCNN
    FASTERCNN
    YOLO

==============Natural language process===========
18) NLTK           : natural language Tool kit
19) Scipy
20) Word2vec(How words will convert into vector)
21) GloVE
22) Wordcloud

==============Hugging face====================
23) Transformers    : BERT (Bi-directional Encoder Representations from Transformers)

============GenAI models=====================
24) OpenAI+Microsoft     : GPT Models
25) Google               : Gemini
26) Amazon               : Q
27) Meta Facebook        : MetaAI
28) Apple                :

LLAMA-Large Language Model Meta AI
GEMMA
Dalle-E
T5
all have different packages

===============LANGCHAIN======================
29) Langchain Framework
    
=============Deployments/applications============
30) Flask
31) Django
32) Streamlit

=============MLops==============================
33) Mlflow
34) Kubeflow
35) Azure AI services    : azure packages
36) GCP                  : GCP packages

**Step-1**

**Create a Dataframe**

- we will create a dataframe using list
- we will create a dataframe using dictionary

In [22]:
import pandas as pd
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [23]:
type(d1)

pandas.core.frame.DataFrame

**Step-2**

**Provide the data**

In [24]:
names=['aarthi','lasya','manasa']
pd.DataFrame(names)

0
0  aarthi
1   lasya
2  manasa

In [25]:
names=['aarthi','lasya','manasa']
age=[21,20,22]
data=zip(names,age)
pd.DataFrame(data)

0   1
0  aarthi  21
1   lasya  20
2  manasa  22

In [26]:
names=['aarthi','lasya','manasa']
age=[21,20,22]
city=['AP','Hyd','Mumbai']
pd.DataFrame(zip(names,age,city))

0   1       2
0  aarthi  21      AP
1   lasya  20     Hyd
2  manasa  22  Mumbai

**Step-3**

**Provide column names**

In [27]:
names=['aarthi','lasya','manasa']
pd.DataFrame(names, columns=['Names'])

Names
0  aarthi
1   lasya
2  manasa

In [28]:
names=['aarthi','lasya','manasa']
age=[21,20,22]
city=['AP','Hyd','Mumbai']
pd.DataFrame(zip(names,age,city),columns=['Names','Age','city'])

Names  Age    city
0  aarthi   21      AP
1   lasya   20     Hyd
2  manasa   22  Mumbai

**Step-4**

**Provide index**

In [29]:
names=['aarthi','lasya','manasa']
age=[21,20,22]
city=['AP','Hyd','Mumbai']
pd.DataFrame(zip(names,age,city),index=['1','2','3'],columns=['Names','Age','city'])

Names  Age    city
1  aarthi   21      AP
2   lasya   20     Hyd
3  manasa   22  Mumbai

In [30]:
names=['aarthi','lasya','manasa']
age=[21,20,22]
city=['AP','Hyd','Mumbai']
df=pd.DataFrame(zip(names,age),index=city,columns=['Names','Age'])

In [31]:
df

Names  Age
AP      aarthi   21
Hyd      lasya   20
Mumbai  manasa   22

**Step-5**

**Add a new column on existing data frame**

In [32]:
#create a dataframe with name ,age and city

In [33]:
import pandas as pd

In [34]:
names=['olive','sam','green']
age=[20,21,22]
city=['Hyd','Blr','MP']
data=zip(names,age,city)
df=pd.DataFrame(data,columns=['Names','Age','City'])
df

Names  Age City
0  olive   20  Hyd
1    sam   21  Blr
2  green   22   MP

- if you want to add a new column
- first check how many rows are there
- for example in above dataframe we have 3 rows
- your new column should also have 3 rows
- suppose i want to create a new column: **salary**
- make a list with 3 values
- salary=[100000,200000,300000]
- **syntax**: dataframe[column]=list of values
- salary=[100000,200000,300000]
- df['salary']=salary

**Step-5: Add new column to existing dataframe**

In [35]:
salary=[100000,200000,300000]
df['salary']=salary
df

Names  Age City  salary
0  olive   20  Hyd  100000
1    sam   21  Blr  200000
2  green   22   MP  300000

**use case-1**
- create empty data frame first
- create 3 list using list comprehension
- lis1= a values from 1 to 10 
- list2= square of 1 to 10
- list3=cube of 1 to 10
- finally make a dataframe

In [36]:
import pandas as pd
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [37]:
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]
df1['X']=l1
df1['Y']=l2
df1['Z']=l3
df1

X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

**Step-6**

**update the already existed column**

- create a new column
    - create a new list
    - df['S']
    - creating a new column the col name is our choice
- update existing column are same way only
    - here also we need to make a list of values=no of rows
    - while updating the existing column
    - we need to provide already existed column name only
    - df['Z']=list of values

In [38]:
# dataframe name: df1
# list of values variable name: z
# which column we want to update : Z'
z=[i**4 for i in range(1,10)]
df1['Z']=z
df1

X   Y     Z
0  1   1     1
1  2   4    16
2  3   9    81
3  4  16   256
4  5  25   625
5  6  36  1296
6  7  49  2401
7  8  64  4096
8  9  81  6561

In [39]:
df2=pd.DataFrame()
l1=[i for i in range(1,10)] # use list comprehension to crea
l2=[i**2 for i in range(1,10)] # use list comprehension to cr
l3=[i**3 for i in range(1,10)] # use list comprehension to creat
df2['Number']=l1 # create column headings X,Y,
df2['Square']=l2
df2['Cube']=l3
df2

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

**Step-7**

**Drop the column**

In [40]:
# How to check the columns
df1.columns

Index(['X', 'Y', 'Z'], dtype='object')

- if u want to drop a specific column
- we will use drop method
- we already the difference b/w keywords and methods
- keywords will use directly
- methods we will use with corresponding dataframe
- **Method name: drop**

d1.drop()
- Column: which column u want to drop
- axis:represents the specified value either row or column
    - axis=0 means rows
    - axis=1 means column
    - by default axis=0
- inplace:will provide overwrite the dataframe or not
    - inplace=True,this indicates overwrite the dataframe
    - inplace=False,this indicates the modified dataframe will be used when u 
      provide new variable

In [41]:
df1.drop('Z')
# we are not providing axis
# it assuming the provided value is a row
# by default axis=0 ==== rows

KeyError: "['Z'] not found in axis"

In [42]:
df1.drop('Z',axis=1)
# after this in a new cell type df1
# you will see original dataframe 
# because we did not provide inplace
# If you want to use below output
# you need to assign a variable
#df_new=df1.drop('X',axis=1)

X   Y
0  1   1
1  2   4
2  3   9
3  4  16
4  5  25
5  6  36
6  7  49
7  8  64
8  9  81

In [43]:
df1.drop('Z',axis=1,inplace=True)
df1

X   Y
0  1   1
1  2   4
2  3   9
3  4  16
4  5  25
5  6  36
6  7  49
7  8  64
8  9  81

**step-8**

**drop the row**
- drop the column and drop the rows both are simliar only
- the only difference is axis
    - axis=0 represents rows
    - by default axis=0 available
    - which means if we provide any value it will represent rows only

In [44]:
#dataframe name:d1

In [45]:
import pandas as pd
df2=pd.DataFrame()
l1=[i for i in range(1,11)]
l2=[i*i for i in range(1,11)]
l3=[i**3 for i in range(1,11)]
df2['Number']=l1
df2['Square']=l2
df2['Cube']=l3
df2

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729
9      10     100  1000

In [46]:
df2.drop('Number')
#if we run this we will get error
#by default axis=0 which rep rows
#but 'Number' is a column

KeyError: "['Number'] not found in axis"

In [47]:
#if u want to drop row then provide row index
df2.drop(4)

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729
9      10     100  1000

In [48]:
#multiple rows 
#multiple columns keep always in a list
df2.drop([4,8])

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512
9      10     100  1000

In [66]:
df2.columns[[0,1]]

Index(['Number', 'Square'], dtype='object')

In [67]:
df2.drop([0,1],axis=1)
#[0,1] rows not rows it is index
#axis=1 columns
#error

KeyError: '[0, 1] not found in axis'

**Step-9**

**How to select the column**

In [68]:
df2['Number']
#series type
#no column name display
#whenever u see this type : series type

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Number, dtype: int64

In [69]:
df2[['Number']]
#Data frame

Number
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10

In [70]:
type(df2['Number'])

pandas.core.series.Series

In [71]:
type(df2[['Number']])

pandas.core.frame.DataFrame

In [72]:
df2.Number

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Number, dtype: int64

- df2['Number']: Series type
- df2[['Number']]: Dataframe type
- df2.Number: Series type

In [74]:
cols=['Number','Square']
df2[cols]

Number  Square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81
9      10     100

In [75]:
df2['Number'].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

- all values comes in an array 
- array means a list of elements only rep numpy package
- generally elements present in 3 ways:
    - List: Basic representation
    - Numpy array: array with numpy package
    - Tensors: tensor flow package
    - Torch: Pytorch package 

In [76]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [77]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [78]:
#tensor([1,2,3,4])

In [79]:
#concat
list1=[1,2,3,4]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [80]:
#adding l1+l2
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [82]:
df2['Number'].values
#imagine we worked on an ML problem
#we got some series of values
#with that that series of values also we can create a dataframe

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [83]:
df2['NUMBER']=df2['Number'].values
df2

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9
9      10     100  1000      10

**Step-10**

**Save the dataframe**
- Dataframes we can save in two formats
    - csv: comma seperated value
    - xlsx: excel format
- In order to save any data
    - where u want to save: directory name
    - what is the name of the file for storing
    - what is the extension
- we already seen same in file handling session

In [ ]:
#Case-1: Saving file at same location where python file is there
#no need to provide directory path
#directly give only name of the file
#and extension

In [84]:
#Dataframe name:df2
#save the data without index column
df2.to_csv('Data1.csv')
df2.to_excel('Data1.xlsx')

**Step-11**

**How to read a dataframe**

In [85]:
import pandas as pd
pd.read_csv('Data1.csv')

Unnamed: 0  Number  Square  Cube  NUMBER
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9
9           9      10     100  1000      10

In [86]:
import os
os.getcwd()

'C:\\Users\\lasya\\Documents\\NareshIT\\EDA'

In [87]:
import pandas as pd
pd.read_excel('Data1.xlsx')

Unnamed: 0  Number  Square  Cube  NUMBER
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9
9           9      10     100  1000      10

**Step-12**

**How to avoid index column**
- while we save the dataframe
- automatically a new column will be created
- we need to avoid so for that use index=False
- Permisssion denied means close the data file from laptop

In [91]:
#Dataframe name:df2
#save the data without index column
df2.to_csv('Data1.csv',index=False)
df2.to_excel('Data1.xlsx',index=False)

In [92]:
#read the data
import pandas as pd
pd.read_csv('Data1.csv')

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9
9      10     100  1000      10